(Graded) Write a Python function that encodes English-language phrases into a form of coded
language called pig Latin. There are many ways to form pig Latin phrases. For simplicity, use
the following algorithm: To form a pig Latin phrase from an English-language phrase,
tokenize the phrase into words with string method split. To translate each English word
into a pig Latin word, place the first letter of the English word at the end of the word and add
the letters “ay.” Thus, the word “jump” becomes “umpjay,” the word “the” becomes “hetay,”
and the word “computer” becomes “omputercay.” If the word starts with a vowel, just add
“ay” at the end of the word. Blanks between words remain as blanks. Assume the following:
The English phrase consists of words separated by blanks, there are no punctuation marks,
and all words have two or more letters. Enable the user to pass a sentence as the input to the
function, then display the sentence in pig Latin.

In [1]:
def pig_latin(translate):
    split_words = translate.split(" ")
    vowels = ('a', 'e', 'i', 'o', 'u')
    out_string = ' '
    for word in split_words:
        if word[0] in vowels:
            out_string += (word + 'ay ')
        else:
            out_string += word[1:] + word[0] + 'ay '
    return out_string
            
to_translate = "this sentence is in pig latin"
print(pig_latin(to_translate))



 histay entencesay isay inay igpay atinlay 


Write a Python function that accepts a five-letter word as its input and produces every
possible three-letter string, based on the word’s letters. For example, the three-letter words
produced from the word “bathe” include, but are not limited to, “ate,” “bat,” “bet,” “tab,”
“hat,” “the,” “tea,” and “aht.”
Challenge: Investigate the functions from the itertools module, then use an appropriate
function to automate this task.

In [85]:
def generate(word):
    three_letter = set()
    for i in range(len(word)):
        for j in range(len(word)):
            for k in range(len(word)):
                if i != j and i != k and j != k:
                    three_letter.add(word[i] + word[j] + word[k])
    return three_letter

print(generate('bathe'))

{'aet', 'hae', 'hba', 'bta', 'bth', 'beh', 'bet', 'tbe', 'eta', 'htb', 'etb', 'eth', 'tah', 'bah', 'bha', 'heb', 'ath', 'eht', 'bae', 'atb', 'hat', 'abt', 'tha', 'tbh', 'tba', 'tae', 'teh', 'het', 'bte', 'tab', 'eba', 'aeb', 'eha', 'ehb', 'ebt', 'bea', 'the', 'abe', 'thb', 'teb', 'abh', 'bhe', 'ate', 'aeh', 'hbt', 'tea', 'eah', 'bat', 'hea', 'ahe', 'ebh', 'hbe', 'hab', 'eab', 'hte', 'bht', 'aht', 'eat', 'hta', 'ahb'}


(Graded) Write a Python script that enables the user to enter mathematical word problems
like “two times three” and “seven minus five”, then use string processing to break apart the
string into the numbers and the operation and return the result. Hence, “two times three”
would return 6, and “seven minus five” would return 2. To keep things simple, assume that
the user enters only the words for the numbers 0 through 9 and only the operations “plus,”
“minus,” “times,” “divided by,” and “raised to.”

In [2]:
def do_math(equation):
    operation = {'plus': '+', 'minus': '-', 'times':'*', 'divided by': '/', 'raised to': '**'}
    numbers = {'zero':'0', 'one': '1', 'two':'2', 'three':'3', 'four':'4', 'five':'5', 'six': '6', 'seven':'7', 'eight': '8', 'nine': '9'}
    eq = equation.split()
    formula = ' '
    for value in eq:
        if value in operation:
            formula += operation[value]
        elif value in numbers:
            formula += numbers[value]
    return eval(formula)


eq = 'nine times three'
do_math(eq)

27

(Graded) Write a Python script that assists the user with some common metric-to-English
conversions. Your script should allow the user to specify the names of the units as strings
(e.g., centimeters, liters, grams, and so on for the metric system and inches, quarts, pounds,
and so on for the English system) and should respond to simple questions, such as “How
many inches are in 2 meters?” and “How many liters are in 10 quarts?” Your script should
recognize invalid conversions. For example, the following question is not meaningful,because “feet” is a unit of length and “kilogram” is a unit of mass: “How many feet are in 5
kilograms?”
Assume that all questions are in the form shown above. Use string processing to capture the
important substrings, such as “inches,” “2,” and “meters” in the first sample question above.
Recall that functions int and float can convert strings to numbers. Your solution does not
have to be comprehensive of all possible conversions; however, it should give a well-written
prototype that could be easily modified to add further functionalities to it.

In [81]:
def calculation(question):
    # Define conversion factors
    conversion = {
        ('meters', 'inches'): 39.3701,
        ('inches', 'meters'): 0.0254,
        ('liters', 'gallons'): 0.264172,
        ('gallons', 'liters'): 3.78541,
        ('quarts', 'liters'): 0.946353,
        ('liters', 'quarts'): 1.05669,
        ('cups', 'liters'): 0.236588,
        ('liters', 'cups'): 4.22675,
        ('kilograms', 'pounds'): 2.20462,
        ('pounds', 'kilograms'): 0.453592,
        ('yards', 'meters'): 0.9144,
        ('meters', 'yards'): 1.09361,
        ('feet', 'meters'): 0.3048,
        ('meters', 'feet'): 3.28084,
        ('inches', 'feet'): 0.0833333,
        ('feet', 'inches'): 12,
        ('cups', 'quarts'): 0.25,
        ('quarts', 'cups'): 4
    }

    # Define valid units
    valid = ['meters', 'inches', 'gallons', 'liters', 'quarts', 
                'cups', 'pounds', 'kilograms', 'yards', 'feet']

    # Split the question into its relevant parts
    split_question = question.split()``
    value = float(split_question[5])
    from_unit = split_question[6][:-1]
    to_unit = split_question[2]

    # Check if units are valid
    if from_unit not in valid or to_unit not in valid:
        return 'Invalid units'

    # Check if conversion factor is available
    if (from_unit, to_unit) not in conversion:
        return 'Invalid conversion'

    # Perform conversion
    factor = conversion[(from_unit, to_unit)]
    result = value * factor

    return f'There are {result} {to_unit} in {value} {from_unit}'

question1 = 'How many inches are in 2 meters?'
question2 = 'How many liters are in 10 quarts?'
question3 = 'How many pounds are in 5 kilograms?'
print(calculation(question1))
print(calculation(question2))
print(calculation(question3))


There are 78.7402 inches in 2.0 meters
There are 9.46353 liters in 10.0 quarts
There are 11.0231 pounds in 5.0 kilograms


Create a 3-by-3 array 𝐀 containing the even integers from 2 through 18, inclusive. Create a
second 3-by-3 array 𝐁 containing the integers from 9 down to 1, inclusive.
(a) Raise each element of the first array 𝐀 by 2 and multiply the result by the second array
elementwise and matrix-wise.
(b) Replace those elements of array 𝐀 in the corresponding positions for which array 𝐁
contains a multiple integer of 3 with their squared root values. Replace those elements of
array 𝐁 in the corresponding positions for which array 𝐀 contains a multiple integer of 4
with their negative values. Multiply the inverse matrix of the result of the first operation
to the inverse matrix of the result of the second operation elementwise and matrix-wise.

(Graded) Let 𝐀 be an 𝑚-by-𝑛 matrix of integer numbers. Write a Python function that accepts
matrix 𝐀 as its input and prints the diagonal elements with negative slope, starting from the
top-right element.
For example, if the 5-by-4 matrix 𝐀 is defined as
𝐀 =
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16
17 18 19 20

then, the following elements of the matrix must be printed:
4
3 8
2 7 12
1 6 11 16
5 10 15 20
9 14 19
13 18
17
Please use an ndarray datatype produced by the NumPy library in your solution (instead of
using a two-dimensional list).

In [27]:
import numpy as np

def sloped_print(list):
    num_elements = np.size(list)
    maxRow, minCol = 0, 3
    # Prints the First Half
    while(num_elements > np.size(list)/2):
        row = 0
        for col in range(minCol, 4):
            if(row <= maxRow):
                print(list[row][col], end = '\t')  
                num_elements -= 1
                row += 1
        print()
        maxRow += 1
        minCol -= 1

    minRow, maxCol = 1, 3
    # Prints the Second Half
    while(num_elements > 0):
        col = 0
        for row in range(minRow, 5):
            if(col <= maxCol):
                print(list[row][col], end = '\t')
                num_elements -= 1
                col += 1
        print()
        minRow += 1
        maxCol -= 1
    
in_list = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16], [17, 18, 19, 20]])
sloped_print(in_list)

4	
3	8	
2	7	12	
1	6	11	16	
5	10	15	20	
9	14	19	
13	18	
17	


(Graded) NumPy arrays offer a mean method, but not a median or mode method.
(a) Write Python functions median and mode that use existing NumPy capabilities to
determine the median (middle) and mode (most frequent) of the values in an array. Your
functions should determine the median and mode values regardless of the array’s shape.
Test your function on three arrays of different shapes with random integers.Modify your functions from Part (a) to allow the user to provide an axis keyword
argument so that the calculations can be performed row-by-row (by default) or column-
by-column on a two-dimensional array.

In [34]:
import numpy as np

def median(in_list, axis = 'row'):
    in_list = np.array(in_list)
    if axis == 'col':
        in_list = in_list.transpose()

    for row in range(len(in_list)):
        if len(in_list[row]) > 0:
            mid_index = len(in_list[row])//2
            if(axis == 'col'):
                if len(in_list[row]) % 2 == 0:
                    median = (in_list[row][mid_index + 1] + in_list[row][mid_index]) / 2
                    print(f'Median for col {row + 1}: {median}') 
                else:
                    print(f'Median for col {row + 1}: {in_list[row][mid_index]}')
            else:
                if len(in_list[row]) % 2 == 0:
                    median = (in_list[row][mid_index + 1] + in_list[row][mid_index]) / 2
                    print(f'Median for row {row + 1}: {median}') 
                else:
                    print(f'Median for row {row + 1}: {in_list[row][mid_index]}') 

def mode(in_list, axis = 'row'):
    if axis == 'col':
        in_list = in_list.transpose()
    
    max_row_length = max(len(row) for row in in_list)
    for row in range(len(in_list)):
        values = set()
        frequency = {}
        for col in range(max_row_length):
            values.add(in_list[row][col])
        for val in values:
            frequency[val] = 0
        for val in in_list[row]:
            if val in values:
                frequency[val] += 1
        max_value = -10000
        max_key = 0
        for key, value in frequency.items():
            if value > max_value:
                max_value = value
                max_key = key
        if(axis == 'col'):
            print(f'The mode for Column {row + 1} is {max_key} with a frequency of {max_value}')
        else:
            print(f'The mode for Row {row + 1} is {max_key} with a frequency of {max_value}')

                
            

rows = np.random.randint(2, 10)
cols = np.random.randint(2, 10)
random_array1 = np.random.randint(1, 7, size = (rows, cols))
print(random_array1)

median(random_array1, 'col')
mode(random_array1)

rows = np.random.randint(2, 10)
cols = np.random.randint(2, 10)
random_array2 = np.random.randint(1, 7, size = (rows, cols))
print(random_array2)

median(random_array2)
mode(random_array2, 'col')

rows = np.random.randint(2, 10)
cols = np.random.randint(2, 10)
random_array3 = np.random.randint(1, 7, size = (rows, cols))
print(random_array3)

median(random_array3, 'col')
mode(random_array3)





[[4 2 6 1 3 5 6 6]
 [3 6 6 2 4 4 5 3]
 [3 3 6 6 3 3 4 1]
 [3 1 5 1 4 1 2 6]
 [2 5 1 2 3 5 2 6]
 [6 3 4 3 1 5 2 3]
 [4 5 4 6 3 6 3 5]
 [1 5 5 1 1 2 1 3]]
Median for col 1: 4.0
Median for col 2: 4.0
Median for col 3: 2.5
Median for col 4: 2.5
Median for col 5: 2.0
Median for col 6: 5.0
Median for col 7: 2.0
Median for col 8: 4.5
The mode for Row 1 is 6 with a frequency of 3
The mode for Row 2 is 3 with a frequency of 2
The mode for Row 3 is 3 with a frequency of 4
The mode for Row 4 is 1 with a frequency of 3
The mode for Row 5 is 2 with a frequency of 3
The mode for Row 6 is 3 with a frequency of 3
The mode for Row 7 is 3 with a frequency of 2
The mode for Row 8 is 1 with a frequency of 4
[[1 6 4 5 2 4 6 6 4]
 [5 4 1 1 3 3 1 5 4]]
Median for row 1: 2
Median for row 2: 3
The mode for Column 1 is 1 with a frequency of 1
The mode for Column 2 is 4 with a frequency of 1
The mode for Column 3 is 1 with a frequency of 1
The mode for Column 4 is 1 with a frequency of 1
The mode for Column 5 is